[project]
name = "ai-q-learning-stock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "tqdm>=4.67.1",
    "yfinance>=0.2.65",
]
